bot:
  locations:
    remote:
      displayName: "Remote"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    us:
      displayName: "US"
      enabledAsGroup: true
      additionalUsers: []
      admins: []
    saratov:
      displayName: "Saratov"
      enabledAsGroup: true
      additionalUsers:
         - U02H6R5DUN9 # kvendingoldo173
      admins:
        - U01THB38EDV
    spb:
      displayName: "Saint Petersburg"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    moscow:
      displayName: "Moscow"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    kazan:
      displayName: "Kazan"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    kharkiv:
      displayName: "Kharkiv"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    lviv:
      displayName: "Lviv"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    kiev:
      displayName: "Kyiv"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    dnipro:
      displayName: "Dnipro"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    gdansk:
      displayName: "Gdansk"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    ljubljana:
      displayName: "Ljubljana"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    wroclaw:
      displayName: "Wroclaw"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    krakow:
      displayName: "Krakow"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    belgrade:
      displayName: "Belgrade"
      enabledAsGroup: true
      additionalUsers: []
      admins: []
    london:
      displayName: "London"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    chisinau:
      displayName: "Chisinau"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    guadalajara:
      displayName: "Guadalajara"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    yerevan:
      displayName: "Yerevan"
      enabledAsGroup: true
      additionalUsers: []
      admins: []

  groups:
    worldwide:
      displayName: "Worldwide"
      enabled: true
      additionalUsers:
        - U01THB38EDV # kvendingoldo
      admins: []
    eng_data_analytics:
      displayName: "ENG: Data Analytics"
      enabled: true
      additionalUsers: []
      admins: []

database:
  host: 127.0.0.1
  port: 3308
  db: coffee
  username: root

daemons:
  week:
    poolPeriod: 10800 # 3h

notifications:
  dryRun: true

devMode:
  enabled: true
  weekday: 5
  hour: 20

log:
  rotation: "1 week"
