bot:
  locations:
    remote:
      displayName: "Remote"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    us:
      displayName: "US"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    saratov:
      displayName: "RU: Saratov"
      enabledAsGroup: true
      additionalUsers:
         - U02H6R5DUN9 # kvendingoldo173
      admins:
        - U01THB38EDV
    spb:
      displayName: "RU: Saint Petersburg"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    moscow:
      displayName: "RU: Moscow"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    kazan:
      displayName: "RU: Kazan"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    kharkiv:
      displayName: "UA: Kharkiv"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    lviv:
      displayName: "UA: Lviv"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    kiev:
      displayName: "UA: Kyiv"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    dnipro:
      displayName: "UA: Dnipro"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    ljubljana:
      displayName: "SI: Ljubljana"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    wroclaw:
      displayName: "PL: Wroclaw"
      enabledAsGroup: true
      additionalUsers: []
      admins: []
    krakow:
      displayName: "PL: Krakow"
      enabledAsGroup: true
      additionalUsers: []
      admins: []
    gdansk:
      displayName: "PL: Gdansk"
      enabledAsGroup: true
      additionalUsers: []
      admins: []
    belgrade:
      displayName: "RS: Belgrade"
      enabledAsGroup: true
      additionalUsers: []
      admins:
        - U4BSUSM5Z
        - UKDHWCUAG
    london:
      displayName: "GB: London"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    chisinau:
      displayName: "MD: Chisinau"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    guadalajara:
      displayName: "MX: Guadalajara"
      enabledAsGroup: false
      additionalUsers: []
      admins: []
    yerevan:
      displayName: "AM: Yerevan"
      enabledAsGroup: true
      additionalUsers: []
      admins:
        - U4BSUSM5Z
        - UKDHWCUAG

  groups:
    worldwide:
      displayName: "Worldwide"
      enabled: true
      additionalUsers:
        - U01THB38EDV # kvendingoldo
      admins: []
    eng_data_analytics:
      displayName: "ENG: Data Analytics"
      enabled: true
      additionalUsers: []
      admins: []

database:
  host: 127.0.0.1
  port: 3308
  db: coffee
  username: root

daemons:
  week:
    poolPeriod: 3600 # 1h

notifications:
  dryRun: true

devMode:
  enabled: true
  weekday: 5
  hour: 20

log:
  rotation: "1 week"
