bot:
  additionalUsers:
    common:
      - U01THB38EDV # kvendingoldo
    saratov:
      - U01THB38EDV # kvendingoldo

database:
  host: 127.0.0.1
  port: 3308
  db: coffee
  username: root

daemons:
  week:
    poolPeriod: 10800 # 3h

notifications:
  dryRun: false

devMode:
  enabled: true
  weekday: 4
  hour: 15

log:
  rotation: "1 week"
