bot:
  additionalUsers:
    - U4BSUSM5Z # Alex Sharov

database:
  host: mysql
  port: 3306
  db: coffee
  username: root

daemons:
  week:
    poolPeriod: 21600 # 6h

notifications:
  dryRun: false

devMode:
  enabled: false
  weekday: 5
  hour: 19
