bot:
  locations:
    remote:
      displayName: "Remote"
      enabledAsGroup: false
      additionalUsers: []
    us:
      displayName: "US"
      enabledAsGroup: false
      additionalUsers: []
    saratov:
      displayName: "Saratov"
      enabledAsGroup: true
      additionalUsers:
         - UKDHWCUAG # ytsvetkova
    spb:
      displayName: "Saint Petersburg"
      enabledAsGroup: false
      additionalUsers: []
    moscow:
      displayName: "Moscow"
      enabledAsGroup: false
      additionalUsers: []
    kazan:
      displayName: "Kazan"
      enabledAsGroup: false
      additionalUsers: []
    kharkiv:
      displayName: "Kharkiv"
      enabledAsGroup: false
      additionalUsers: []
    lviv:
      displayName: "Lviv"
      enabledAsGroup: false
      additionalUsers: []
    kiev:
      displayName: "Kyiv"
      enabledAsGroup: false
      additionalUsers: []
    dnipro:
      displayName: "Dnipro"
      enabledAsGroup: false
      additionalUsers: []
    gdansk:
      displayName: "Gdansk"
      enabledAsGroup: false
      additionalUsers: []
    ljubljana:
      displayName: "Ljubljana"
      enabledAsGroup: false
      additionalUsers: []
    wroclaw:
      displayName: "Wroclaw"
      enabledAsGroup: false
      additionalUsers: []
    krakow:
      displayName: "Krakow"
      enabledAsGroup: false
      additionalUsers: []
    belgrade:
      displayName: "Belgrade"
      enabledAsGroup: true
      additionalUsers: []
    london:
      displayName: "London"
      enabledAsGroup: false
      additionalUsers: []
    chisinau:
      displayName: "Chisinau"
      enabledAsGroup: false
      additionalUsers: []
    guadalajara:
      displayName: "Guadalajara"
      enabledAsGroup: false
      additionalUsers: []

  groups:
    worldwide:
      displayName: "Worldwide"
      enabled: true
      additionalUsers: []
    eng_data_analytics:
      displayName: "ENG: Data Analytics"
      enabled: true
      additionalUsers: []

database:
  host: mysql
  port: 3306
  db: coffee
  username: root

daemons:
  week:
    poolPeriod: 10800 # 3h

notifications:
  dryRun: false

devMode:
  enabled: false
  weekday: 5
  hour: 19

log:
  rotation: "1 week"
