version: '3.1'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffee
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 50m
  app:
    build: .
    restart: always
    volumes:
      - ~/bot/config.yml:/home/rcb/bot/config.yml
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 50m