version: '3.1'
services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffee
    ports:
      - "3306:3306"
    volumes:
      - ~/bot/sql:/docker-entrypoint-initdb.d/:rw
  app:
    container_name: bot
    image: rcb:${BOT_VERSION}
    restart: always
    volumes:
      - ~/bot/resources/config.yml:/home/rcb/bot/resources/config.yml
      - ~/bot/resources/.env:/home/rcb/bot/.env

# TODO: rework it
#config = config.load("../resources/config.yml", "../.env")
