version: '3.1'
services:
  mysql:
    container_name: rcb-mysql
    image: mysql:8.0
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffee
      TZ: Etc/GMT-1
    ports:
      - "3308:3306"
    volumes:
      - ${BOT_HOME}/sql:/docker-entrypoint-initdb.d/:rw
      - ${BOT_HOME}/mysql_data:/var/lib/mysql
  app:
    container_name: bot
    image: kvendingoldo/rcb:${BOT_VERSION}
    restart: always
    env_file:
      - ${BOT_HOME}/resources/.env
    environment:
        RCB_LOG_DIR: /home/rcb/bot/logs
        TZ: Etc/GMT-1
    volumes:
      - ${BOT_HOME}/resources/config.yml:/home/rcb/bot/resources/config.yml
      - ${BOT_HOME}/logs:/home/rcb/bot/logs
