version: '3.1'
services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffee
    ports:
      - "3306:3306"
    volumes:
      - ~/bot/sql:/docker-entrypoint-initdb.d/:rw
    logging:
      options:
        max-size: 50m
  app:
    container_name: bot
    restart: always
    volumes:
      - ~/bot/config.yml:/home/rcb/bot/config.yml
    logging:
      options:
        max-size: 50m
