name: pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.set_version.outputs.safe_version }}
    steps:
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.9
      -
        name: Print image version
        run: echo ${{ steps.set_version.outputs.safe_version }}
